version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fastapi_server
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - ./server/models:/app/models # Modèles utilisés par le backend
      - ./data:/app/data # Données partagées

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: streamlit_client
    ports:
      - "8501:8501"
    depends_on:
      - server
    volumes:
      - ./server:/app/server # Accès au code du serveur
      - ./data:/app/data # Données partagées
      - ./server/models:/app/server/models # Modèles utilisés par le backend
