version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  server:
    build: ./server
    container_name: fastapi_server
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: streamlit_client
    ports:
      - "8501:8501"
    depends_on:
      - server
